;;; my-calendar.el
;;;
;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; (defvar calendar-mode-map
  ; (let ((map (make-keymap)))
    ; (suppress-keymap map)
    ; (dolist (c '(narrow-to-region mark-word mark-sexp mark-paragraph
                 ; mark-defun mark-whole-buffer mark-page
                 ; downcase-region upcase-region kill-region
                 ; copy-region-as-kill capitalize-region write-region))
      ; (define-key map (vector 'remap c) 'calendar-not-implemented))
    ; (define-key map "<"     'calendar-scroll-right)
    ; (define-key map "\C-x<" 'calendar-scroll-right)
    ; (define-key map [prior] 'calendar-scroll-right-three-months)
    ; (define-key map "\ev"   'calendar-scroll-right-three-months)
    ; (define-key map ">"     'calendar-scroll-left)
    ; (define-key map "\C-x>" 'calendar-scroll-left)
    ; (define-key map [next]  'calendar-scroll-left-three-months)
    ; (define-key map "\C-v"  'calendar-scroll-left-three-months)
    ; (define-key map "\C-b"  'calendar-backward-day)
    ; (define-key map "\C-p"  'calendar-backward-week)
    ; (define-key map "\e{"   'calendar-backward-month)
    ; (define-key map "\C-x[" 'calendar-backward-year)
    ; (define-key map "\C-f"  'calendar-forward-day)
    ; (define-key map "\C-n"  'calendar-forward-week)
    ; (define-key map [left]  'calendar-backward-day)
    ; (define-key map [up]    'calendar-backward-week)
    ; (define-key map [right] 'calendar-forward-day)
    ; (define-key map [down]  'calendar-forward-week)
    ; (define-key map "\e}"   'calendar-forward-month)
    ; (define-key map "\C-x]" 'calendar-forward-year)
    ; (define-key map "\C-a"  'calendar-beginning-of-week)
    ; (define-key map "\C-e"  'calendar-end-of-week)
    ; (define-key map "\ea"   'calendar-beginning-of-month)
    ; (define-key map "\ee"   'calendar-end-of-month)
    ; (define-key map "\e<"   'calendar-beginning-of-year)
    ; (define-key map "\e>"   'calendar-end-of-year)
    ; (define-key map "\C-@"  'calendar-set-mark)
    ; ;; Many people are used to typing C-SPC and getting C-@.
    ; (define-key map [?\C-\s] 'calendar-set-mark)
    ; (define-key map "\C-x\C-x" 'calendar-exchange-point-and-mark)
    ; (define-key map "\e=" 'calendar-count-days-region)
    ; (define-key map "gd"  'calendar-goto-date)
    ; (define-key map "gD"  'calendar-goto-day-of-year)
    ; (define-key map "gj"  'calendar-julian-goto-date)
    ; (define-key map "ga"  'calendar-astro-goto-day-number)
    ; (define-key map "gh"  'calendar-hebrew-goto-date)
    ; (define-key map "gi"  'calendar-islamic-goto-date)
    ; (define-key map "gb"  'calendar-bahai-goto-date)
    ; (define-key map "gC"  'calendar-chinese-goto-date)
    ; (define-key map "gk"  'calendar-coptic-goto-date)
    ; (define-key map "ge"  'calendar-ethiopic-goto-date)
    ; (define-key map "gp"  'calendar-persian-goto-date)
    ; (define-key map "gc"  'calendar-iso-goto-date)
    ; (define-key map "gw"  'calendar-iso-goto-week)
    ; (define-key map "gf"  'calendar-french-goto-date)
    ; (define-key map "gml"  'calendar-mayan-goto-long-count-date)
    ; (define-key map "gmpc" 'calendar-mayan-previous-round-date)
    ; (define-key map "gmnc" 'calendar-mayan-next-round-date)
    ; (define-key map "gmph" 'calendar-mayan-previous-haab-date)
    ; (define-key map "gmnh" 'calendar-mayan-next-haab-date)
    ; (define-key map "gmpt" 'calendar-mayan-previous-tzolkin-date)
    ; (define-key map "gmnt" 'calendar-mayan-next-tzolkin-date)
    ; (define-key map "Aa"   'appt-add)
    ; (define-key map "Ad"   'appt-delete)
    ; (define-key map "S"   'calendar-sunrise-sunset)
    ; (define-key map "M"   'calendar-lunar-phases)
    ; (define-key map " "   'scroll-other-window)
    ; (define-key map [?\S-\ ] 'scroll-other-window-down)
    ; (define-key map "\d"  'scroll-other-window-down)
    ; (define-key map "\C-c\C-l" 'calendar-redraw)
    ; (define-key map "."   'calendar-goto-today)
    ; (define-key map "o"   'calendar-other-month)
    ; (define-key map "q"   'calendar-exit)
    ; (define-key map "a"   'calendar-list-holidays)
    ; (define-key map "h"   'calendar-cursor-holidays)
    ; (define-key map "x"   'calendar-mark-holidays)
    ; (define-key map "u"   'calendar-unmark)
    ; (define-key map "m"   'diary-mark-entries)
    ; (define-key map "d"   'diary-view-entries)
    ; (define-key map "D"   'diary-view-other-diary-entries)
    ; (define-key map "s"   'diary-show-all-entries)
    ; (define-key map "pd"  'calendar-print-day-of-year)
    ; (define-key map "pC"  'calendar-chinese-print-date)
    ; (define-key map "pk"  'calendar-coptic-print-date)
    ; (define-key map "pe"  'calendar-ethiopic-print-date)
    ; (define-key map "pp"  'calendar-persian-print-date)
    ; (define-key map "pc"  'calendar-iso-print-date)
    ; (define-key map "pj"  'calendar-julian-print-date)
    ; (define-key map "pa"  'calendar-astro-print-day-number)
    ; (define-key map "ph"  'calendar-hebrew-print-date)
    ; (define-key map "pi"  'calendar-islamic-print-date)
    ; (define-key map "pb"  'calendar-bahai-print-date)
    ; (define-key map "pf"  'calendar-french-print-date)
    ; (define-key map "pm"  'calendar-mayan-print-date)
    ; (define-key map "po"  'calendar-print-other-dates)
    ; (define-key map "id"  'diary-insert-entry)
    ; (define-key map "iw"  'diary-insert-weekly-entry)
    ; (define-key map "im"  'diary-insert-monthly-entry)
    ; (define-key map "iy"  'diary-insert-yearly-entry)
    ; (define-key map "ia"  'diary-insert-anniversary-entry)
    ; (define-key map "ib"  'diary-insert-block-entry)
    ; (define-key map "ic"  'diary-insert-cyclic-entry)
    ; (define-key map "ihd" 'diary-hebrew-insert-entry)
    ; (define-key map "ihm" 'diary-hebrew-insert-monthly-entry)
    ; (define-key map "ihy" 'diary-hebrew-insert-yearly-entry)
    ; (define-key map "iid" 'diary-islamic-insert-entry)
    ; (define-key map "iim" 'diary-islamic-insert-monthly-entry)
    ; (define-key map "iiy" 'diary-islamic-insert-yearly-entry)
    ; (define-key map "iBd" 'diary-bahai-insert-entry)
    ; (define-key map "iBm" 'diary-bahai-insert-monthly-entry)
    ; (define-key map "iBy" 'diary-bahai-insert-yearly-entry)
    ; (define-key map "?"   'calendar-goto-info-node)
    ; (define-key map "Hm" 'cal-html-cursor-month)
    ; (define-key map "Hy" 'cal-html-cursor-year)
    ; (define-key map "tm" 'cal-tex-cursor-month)
    ; (define-key map "tM" 'cal-tex-cursor-month-landscape)
    ; (define-key map "td" 'cal-tex-cursor-day)
    ; (define-key map "tw1" 'cal-tex-cursor-week)
    ; (define-key map "tw2" 'cal-tex-cursor-week2)
    ; (define-key map "tw3" 'cal-tex-cursor-week-iso) ; FIXME twi ?
    ; (define-key map "tw4" 'cal-tex-cursor-week-monday) ; twm ?
    ; (define-key map "twW" 'cal-tex-cursor-week2-summary)
    ; (define-key map "tfd" 'cal-tex-cursor-filofax-daily)
    ; (define-key map "tfw" 'cal-tex-cursor-filofax-2week)
    ; (define-key map "tfW" 'cal-tex-cursor-filofax-week)
    ; (define-key map "tfy" 'cal-tex-cursor-filofax-year)
    ; (define-key map "ty" 'cal-tex-cursor-year)
    ; (define-key map "tY" 'cal-tex-cursor-year-landscape)

    ; (define-key map [menu-bar edit] 'undefined)
    ; (define-key map [menu-bar search] 'undefined)

    ; (easy-menu-define nil map nil cal-menu-sunmoon-menu)
    ; (easy-menu-define nil map nil cal-menu-diary-menu)
    ; (easy-menu-define nil map nil cal-menu-holidays-menu)
    ; (easy-menu-define nil map nil cal-menu-goto-menu)
    ; (easy-menu-define nil map nil cal-menu-scroll-menu)

    ; ;; These are referenced in the default calendar-date-echo-text.
    ; (define-key map [down-mouse-3]
      ; (easy-menu-binding cal-menu-context-mouse-menu))
    ; (define-key map [down-mouse-2]
      ; (easy-menu-binding cal-menu-global-mouse-menu))

    ; ;; cf scroll-bar.el.
    ; (if (and (boundp 'x-toolkit-scroll-bars) x-toolkit-scroll-bars)
        ; (define-key map [vertical-scroll-bar mouse-1]
          ; 'calendar-scroll-toolkit-scroll)
      ; ;; Left-click moves us forward in time, right-click backwards.
      ; (define-key map [vertical-scroll-bar mouse-1] 'calendar-scroll-left)
      ; (define-key map [vertical-scroll-bar drag-mouse-1] 'calendar-scroll-left)
      ; ;; down-mouse-2 stays as scroll-bar-drag.
      ; (define-key map [vertical-scroll-bar mouse-3] 'calendar-scroll-right)
      ; (define-key map [vertical-scroll-bar drag-mouse-3]
        ; 'calendar-scroll-right))
    ; map)
  ; "Keymap for `calendar-mode'.")
